# Generated by Django 4.1.3 on 2022-11-26 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('party', '0003_student'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itemmodel',
            options={'verbose_name_plural': 'Item Modal'},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name_plural': 'Student Information'},
        ),
        migrations.AddField(
            model_name='student',
            name='photo',
            field=models.CharField(default='', max_length=254),
            preserve_default=False,
        ),
    ]
